# Generated by Django 2.0.1 on 2018-01-15 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pollingSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classNumber', models.CharField(max_length=20, unique=True)),
                ('className', models.CharField(default=models.CharField(max_length=20, unique=True), max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('studentID', models.IntegerField(unique=True)),
                ('classrooms', models.ManyToManyField(to='pollingSite.Classroom')),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='key',
            field=models.CharField(default='', max_length=6, unique=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='startTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='stopTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingSite.Instructor'),
        ),
        migrations.AddField(
            model_name='answer',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingSite.Poll'),
        ),
        migrations.AddField(
            model_name='answer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingSite.Student'),
        ),
        migrations.AddField(
            model_name='poll',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pollingSite.Classroom'),
        ),
    ]
