# Generated by Django 2.0.1 on 2018-02-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollingSite', '0003_add_phone_remove_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='correct',
            field=models.IntegerField(default=1),
        ),
    ]
