# Generated by Django 2.0.2 on 2018-02-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollingSite', '0004_poll_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='key',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
