# Generated by Django 2.0.1 on 2018-02-19 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollingSite', '0005_auto_20180219_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='classKey',
        ),
    ]
