# Generated by Django 2.0.1 on 2018-02-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollingSite', '0013_classroom_classkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='classKey',
            field=models.CharField(default='123456', max_length=6, unique=True),
        ),
    ]
