# Generated by Django 2.0.2 on 2018-02-19 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollingSite', '0014_auto_20180219_1400'),
        ('pollingSite', '0006_auto_20180206_1824'),
    ]

    operations = [
    ]
