# Generated by Django 2.0.2 on 2018-02-19 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollingSite', '0015_merge_20180219_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='key',
        ),
    ]
