# Generated by Django 2.0.2 on 2018-02-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollingSite', '0016_remove_poll_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='quarter',
            field=models.IntegerField(choices=[(0, 'Winter'), (1, 'Spring'), (2, 'Summer'), (3, 'Fall')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='year',
            field=models.IntegerField(choices=[(2018, 2018)], default=2018),
            preserve_default=False,
        ),
    ]
