# Generated by Django 2.0.1 on 2018-02-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollingSite', '0018_auto_20180220_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='className',
            field=models.CharField(default=models.CharField(default='', max_length=20), max_length=64),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='classNumber',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='poll',
            name='correct',
            field=models.IntegerField(default=0),
        ),
    ]
