# Generated by Django 2.0.1 on 2018-02-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollingSite', '0019_auto_20180225_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lastname',
            field=models.CharField(default='smith', max_length=128),
        ),
    ]
